### ISSUE TITLE
is it possible to use spinner instead of message?

### ISSUE THREAD

**Issue by 0xori** [nygardk/react-loader-advanced#1]
Hi,
I Love your work! 
Can I use another component i.e spinner instead of the loading message?
Thanks!

**Comment by nygardk** [comment]
Hi,
Thanks!

Yes, you can use any element you want, e.g.:

```
var spinner = (
    <span>this-would-be-your-spinner</span>
);

<Loader message={spinner}>
...
</Loader>
```

**Comment by 0xori** [comment]
Awesome! Thanks!
