### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by hoeck** [nygardk/react-loader-advanced#10]
Hi, thanks for writing this component. Been using it with a React + Typescript app and was just wondering if you would accept a PR that adds type information (a single index.d.ts file, looking a bit like [this](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-loader/index.d.ts) one)?

**Comment by nygardk** [comment]
Hi. Yes, I would accept such PR. Thanks.

**Comment by hoeck** [comment]
Hey, thanks for merging my PR, just did a yarn upgrade and could delete my local adhoc typedefs :smile: :thumbsup:.
