### ISSUE TITLE
TransitionConfig is a required prop?

### ISSUE THREAD

**Issue by tsneed290** [nygardk/react-loader-advanced#15]
I started seeing these warnings in my tests recently:

```
console.error node_modules/fbjs/lib/warning.js:33
      Warning: Failed prop type: The prop `transitionConfig` is marked as required in `Loader`, but its value is `undefined`.
          in Loader
```

Is transitionConfig now required on all usages? 

I found the change in this diff: https://github.com/nygardk/react-loader-advanced/commit/ec0bd466850e8a2da22548f01928028b9e9e86ed

**Comment by holyman2k** [comment]
I'm not clear what's the possible transitionName, can some one give an example please?

**Comment by telmogh** [comment]
You can use like this:
```
<Loader
  show={this.isRequestingApi}
  message={`Loading...`}
  transitionConfig={{
    transitionName: 'all',
    transitionEnterTimeout: 2,
    transitionLeaveTimeout: 4,
  }}
/>
```

**Comment by tsneed290** [comment]
In an attempt to keep this issue on track, I should refine my question.

Why is this now required? Can't we use some notion of prop defaults so we don't break existing code when it wasn't required before? From the [documentation](https://github.com/nygardk/react-loader-advanced#options-props), `props.show` is the only required property.

**Comment by nygardk** [comment]
Sorry, it was made required by accident. Fixed in v. 1.7.1.

**Comment by tsneed290** [comment]
Thanks @nygardk!
