### ISSUE TITLE
Ability to override loader content div styles

### ISSUE THREAD

**Issue by jayalfredprufrock** [nygardk/react-loader-advanced#3]
Hi I've been enjoying your component, but I recently came across a need to alter the loader__content div styles by adding "height: 100%". Since you provided classes I was able to accomplish it using a stylesheet, however I'm using inline styles everywhere else so I hate to have a stylesheet just for this one little fix.

I'd be happy to submit a pull request for the ability to override the content container via props if I thought you'd accept it. Or perhaps having the content div include "height: 100%" would be good default behavior. 

Regardless, thanks for all your work!

**Comment by nygardk** [comment]
Hi,

Thanks for the comment! I added `contentStyle` and `messageStyle` props in version `1.4.0`.
