### ISSUE TITLE
Console error when setting foregroundStyle of only one loader

### ISSUE THREAD

**Issue by donnapep** [nygardk/react-loader-advanced#4]
I added the Loader as follows:

```
<Loader show={this.props.page.isFetching} message={spinner} hideContentOnLoad={true} backgroundStyle={{backgroundColor: 'transparent'}} foregroundStyle={{color: '#333'}}>
  <About page={this.props.page} about={this.props.about} social={this.props.social} />
</Loader>
```

When this runs, I receive the following error in the console:

> Warning: `div` was passed a style object that has previously been mutated. Mutating `style` is deprecated. Consider cloning it beforehand. Check the `render` of `Loader`. Previous style: {display: "table", width: "100%", height: "100%", textAlign: "center", zIndex: 20, color: "#333"}. Mutated style: {display: "table", width: "100%", height: "100%", textAlign: "center", zIndex: 20, color: "transparent"}.

**Comment by donnapep** [comment]
Note that this only occurs if you have more than one spinner and the other spinner does not also set the `foregroundStyle` attribute.

**Comment by nygardk** [comment]
Could you try with version 1.4.1 and report if the problem still exists?
