### ISSUE TITLE
fade in/fade out

### ISSUE THREAD

**Issue by beckend** [nygardk/react-loader-advanced#5]
Possible to enhance and use `ReactTransitionGroup` to do mount/unmount animations on the loader div?
Maybe the callbacks can be to add some class/styles object -  when hiding or showing the loader.
It will end up looking much smoother.

**Comment by jayalfredprufrock** [comment]
I'd also love to see some kind of debounce timer that would prevent showing the loader in cases where the loading prop is set to true for less than some configurable amount of time. It can be distracting when the loader is visible for so little time that you can't even read the loading text...

**Comment by nygardk** [comment]
Hey, I'm gonna look at these improvements soon!

**Comment by nygardk** [comment]
@beckend, @jayalfredprufrock version 1.6.0 now released, which supports setting fade animation with `transitionConfig` prop. See demo0!
