### ISSUE TITLE
import { EventEmitter } from 'events' dependency issue

### ISSUE THREAD

**Issue by MichaelRando** [nygardk/react-loader-advanced#8]
When I linked against this component for a browser app, a global 'events' object was used in my bundle.js that I had not installed. I installed an events lib to see if that would fix the require(), but it did not. Is this an unresolved devDependency, or a moved package within React? 

I'm building with rollupjs rather than webpack, fyi.

**Comment by ZephD** [comment]
events is a default node module
https://www.npmjs.com/package/events

**Comment by MichaelRando** [comment]
It is. That's why requiring it in a browser app seems stupid.

**Comment by nygardk** [comment]
Fixed in `v1.7.0`.
